// User authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";

// Orders
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const COMPLETE_ORDER_ERROR = "COMPLETE_ORDER_ERROR";
export const COMPLETE_ORDER_SUCCESS = "COMPLETE_ORDER_SUCCESS";
export const CANCEL_ORDER_ERROR = "CANCEL_ORDER_ERROR";
export const CLEAR_TOASTS = "CLEAR_TOASTS";

// Personal information edit
export const INFO_UPDATE_ERROR = "INFO_UPDATE_ERROR";
export const CLEAR_UPDATE_ERROR = "CLEAR_UPDATE_ERROR";

// Password reset
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";
export const CLEAR_FEEDBACK = "CLEAR_FEEDBACK";
export const VERIFY_LINK_SUCCESS = "VERIFY_LINK_SUCCESS";
export const VERIFY_LINK_ERROR = "VERIFY_LINK_ERROR";
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_ERROR = "PASSWORD_UPDATE_ERROR";
export const SET_LOADING = "SET_LOADING";
